- fail: You must define your Opsmatic Integration token variable
  when: opsmatic_integration_token == ""

- include: debian.yml
  when: ansible_os_family == "Debian"

- include: rhel.yml
  when: ansible_os_family == "RedHat"

- name: create global config
  template: src=opsmatic-global.j2 dest=/etc/default/opsmatic-global

- include: agent.yml

- include: cli.yml
  when: opsmatic_install_cli == true